name: Build Kivy App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование исходного кода вашего репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Кэширование зависимостей Buildozer
      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      # Шаг 3: Сборка APK с помощью актуальной ветки master (исправляет проблему с apt update)
      - name: Build Android APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@master
        with:
          command: buildozer android debug

      # Шаг 4: Выгрузка готового файла .apk в артефакты GitHub
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-Android-APK
          path: bin/*.apk